apiVersion: v1
kind: ConfigMap
metadata:
  name: countryinfo-config
  namespace: ncba-countryinfo
data:
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "countryinfo"
  SPRING_PROFILES_ACTIVE: "prod"
  JPA_DDL_AUTO: "update"
  SOAP_ENDPOINT: "http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso"
  SOAP_CONNECT_TIMEOUT_MS: "5000"
  SOAP_READ_TIMEOUT_MS: "10000"
