apiVersion: v1
kind: Secret
metadata:
  name: countryinfo-secret
  namespace: ncba-countryinfo
type: Opaque
stringData:
  DB_USERNAME: "appuser"
  DB_PASSWORD: "apppass"
  MYSQL_ROOT_PASSWORD: "rootpass"
